name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mohamedamineblibech/docker-image-autobuild:latest
    - name: Push the Docker image
      run: docker login -u $USERNAME  -p $PWD && docker push mohamedamineblibech/docker-image-autobuild:latest

